=== NLueg/FernuniHagen/1.semester/01873_DDM/aufgaben/ke3/aufgabe1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT buch (kapitel+)>
<!ELEMENT kapitel (ueberschrift, absatz+)>
        <!ELEMENT ueberschrift (#PCDATA)>
        <!ELEMENT absatz (#PCDATA)>
<!ATTLIST buch verlag CDATA #REQUIRED>
<!ATTLIST kapitel type CDATA #IMPLIED>

=== NLueg/FernuniHagen/1.semester/01873_DDM/aufgaben/ke3/aufgabe1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE buch SYSTEM "aufgabe1.dtd">
<buch verlag="O'Reilly">
  <kapitel type="na">
    <ueberschrift>Vorwort</ueberschrift>
    <absatz>...</absatz>
  </kapitel>
  <kapitel type="xml">
    <ueberschrift>XML Terminologie</ueberschrift>
    <absatz>...</absatz>
  </kapitel>
  <kapitel>
    <ueberschrift>XML Terminologie</ueberschrift>
    <absatz>...</absatz>
  </kapitel>
  <kapitel type="java">
    <ueberschrift>Java Referenz</ueberschrift>
    <absatz>...</absatz>
  </kapitel>
</buch>
